### ISSUE TITLE
Add citation for package

### ISSUE THREAD

**Issue by prvernier** [beaconsproject/beaconstools#49]
This would be very useful for referencing the tools in papers. For example, see https://prioritizr.net/

**Comment by edwardsmarc** [comment]
Related to adding pkgdown. See #41

**Comment by edwardsmarc** [comment]
We might also want to consider adding the vignettes to the pkgdown site, instead of building them every time someone calls install_github. The vignettes take a long time to run and as far as I can tell, there is no way to simply include the already rendered html of the vignette when using install_github(). You have to use the build_vignettes argument which knits the rmd every time.
